runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /(.*\.(html|gif|png|jpg|css|js))$
  static_files: \1
  upload: .*\.(html|gif|png|jpg|css|js)$

